/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta.spk;

import java.sql.ResultSet;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class penerima_raskin extends javax.swing.JInternalFrame {

    /**
     * Creates new form penerima_raskin
     */
    public penerima_raskin() {
        initComponents();
        selectData();
    }
    
    public String autonumber(){
        String sql = "SELECT ID_CALON FROM calon ORDER BY ID_CALON DESC";
        ResultSet rs = Database.executeQuery(sql);
        String idcalon = null;
        
        try {
            if (rs.next()) {
                String number = rs.getString("ID_CALON").substring(5);
                String new_number = "" + (Integer.parseInt(number) + 1);

               idcalon = "calon" + new_number;//sesuaikan dengan variable namenya
            } else {
               idcalon = "calon1";//sesuaikan dengan variable namenya
            }
        rs.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        return idcalon;
    }
    
    public void selectData(){
        String kolom[] = {"Nomor KTP","Nama"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT noktp,nama FROM calon";
        ResultSet rs = Database.executeQuery(SQL);
        try {
            while (rs.next()) {
                String noktp = rs.getString(1);
                String nama = rs.getString(2);
                
                String data[] = {noktp,nama};
                dtm.addRow(data);
            }
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
        }
        tabelData.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NoKTP = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Tanah = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Lantai = new javax.swing.JComboBox<>();
        Dinding = new javax.swing.JComboBox<>();
        Pekerjaan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Penghasilan = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(600, 528));
        setPreferredSize(new java.awt.Dimension(600, 528));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Data Calon Penerima Beras Miskin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Detail Data Calon Penerima");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Nomor KTP kepala keluarga");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Nama kepala keluarga");

        jLabel5.setText("Luas tanah yang dimiliki");

        jLabel6.setText("Jenis lantai yang digunakan");

        jLabel7.setText("Jenis dinding yang digunakan");

        jLabel8.setText("Jenis pekerjaan kepala keluarga");

        jLabel9.setText("Besar penghasilan keluarga per bulan");

        NoKTP.setText("-- Silahkan isi nomor KTP --");
        NoKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoKTPActionPerformed(evt);
            }
        });

        Nama.setText("-- Silahkan isi nama --");

        Tanah.setText("-- Silahkan isi luas tanah --");

        jLabel10.setText("m2");

        Lantai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Silahkan pilih jenis lantai --", "Tanah", "Bambu", "Plester", "Keramik" }));

        Dinding.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Silahkan pilih jenis dinding --", "Bambu", "Rumbia", "Kayu Sengon", "Tembok tanpa diplester" }));

        Pekerjaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Silahkan pilih jenis pekerjaan --", "Buruh", "Petani", "PNS", "Wirausaha" }));

        jLabel11.setText("Rp.");

        Penghasilan.setText("-- Silahkan masukan besar penghasilan --");
        Penghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenghasilanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lantai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dinding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Penghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Tanah, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(NoKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(146, 146, 146))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoKTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Lantai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Dinding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(Penghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Tambah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tambah.setText("Tambah data baru");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Update.setText("Pembaruan data");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Hapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Hapus.setText("Hapus data");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Clear.setText("Bersihkan data panel");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"sekian", "siapa"},
                {"sekian", "siapa"},
                {"sekian", "siapa"},
                {"sekian", "siapa"}
            },
            new String [] {
                "Nomor KTP", "Nama"
            }
        )
        {public boolean isCellEditable(int row, int column){
            return false;
        }}
    );
    tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tabelDataMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tabelData);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(74, 74, 74)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(39, 39, 39)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGap(0, 20, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoKTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoKTPActionPerformed

    private void PenghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PenghasilanActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        //ID
        String id = autonumber();
        
        //normalisasi_tanah
        String tanah = Tanah.getText();
        int ktanah = Integer.parseInt(tanah);
        int ntanah = 0;
        
        if (ktanah < 20 ){
            ntanah = 4;
        }
        if (ktanah > 19 && ktanah <31 ){
            ntanah = 3;
        }
        if (ktanah > 30 && ktanah <41 ){
            ntanah = 2;
        }
        if (ktanah > 40 ){
            ntanah = 1;
        }
        
        //normalisasi_lantai
        String lantai = Lantai.getSelectedItem().toString();
        int nlantai = 0;
        
        if (lantai.equals("Tanah")){
            nlantai = 4;
        }
        if (lantai.equals("Bambu")){
            nlantai = 3;
        }
        if (lantai.equals("Plester")){
            nlantai = 2;
        }
        if (lantai.equals("Keramik")){
            nlantai = 1;
        }
        
        //normalisasi_dinding
        String dinding = Dinding.getSelectedItem().toString();
        int ndinding = 0;
        
        if (dinding.equals("Bambu")){
            ndinding = 4;
        }
        if (dinding.equals("Rumbia")){
            ndinding = 3;
        }
        if (dinding.equals("Kayu Sengon")){
            ndinding = 2;
        }
        if (dinding.equals("Tembok tanpa diplester")){
            ndinding = 1;
        }
        
        //normalisasi_pekerjaan
        String pekerjaan = Pekerjaan.getSelectedItem().toString();
        int npekerjaan = 0;
        
        if (pekerjaan.equals("Buruh")){
            npekerjaan = 4;
        }
        if (pekerjaan.equals("Petani")){
            npekerjaan = 3;
        }
        if (pekerjaan.equals("PNS")){
            npekerjaan = 2;
        }
        if (pekerjaan.equals("Wirausaha")){
            npekerjaan = 1;
        }
        
        //normalisasi_penghasilan
        String penghasilan = Penghasilan.getText();
        int kpenghasilan = Integer.parseInt(penghasilan);
        int npenghasilan = 0;
        
        if (kpenghasilan < 500000 ){
            npenghasilan = 4;
        }
        if (kpenghasilan > 499999 && kpenghasilan <1000001 ){
            npenghasilan = 3;
        }
        if (kpenghasilan > 1000000 && kpenghasilan <3000001 ){
            npenghasilan = 2;
        }
        if (kpenghasilan > 3000000 ){
            npenghasilan = 1;
        }
        
        //preferensi
        int preferensi = 0;
        
        //add_data
        String SQL = "INSERT INTO calon (ID_CALON,NOKTP,NAMA,TANAH,LANTAI,DINDING,PEKERJAAN,PENGHASILAN,"+
                "NTANAH,NLANTAI,NDINDING,NPEKERJAAN,NPENGHASILAN,PREFERENSI)"
                    + "VALUES"
                    + "('"+id+"',"
                    + "'"+NoKTP.getText()+"',"
                    + "'"+Nama.getText()+"',"
                    + "'"+Tanah.getText()+"',"
                    + "'"+Lantai.getSelectedItem().toString()+"',"
                    + "'"+Dinding.getSelectedItem().toString()+"',"
                    + "'"+Pekerjaan.getSelectedItem().toString()+"',"
                    + "'"+Penghasilan.getText()+"',"
                    + "'"+ntanah+"',"
                    + "'"+nlantai+"',"
                    + "'"+ndinding+"',"
                    + "'"+npekerjaan+"',"
                    + "'"+npenghasilan+"',"
                    + "'"+preferensi+"')";
        Database.execute(SQL);
        selectData();
    }//GEN-LAST:event_TambahActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        System.out.println(autonumber());
    }//GEN-LAST:event_ClearActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        int baris = tabelData.getSelectedRow();
        
        try {
            String SQL = "SELECT noktp,nama,tanah,lantai,dinding,pekerjaan,penghasilan FROM calon WHERE noktp = '" +
                    tabelData.getValueAt(baris, 0).toString()+"'";
            ResultSet rs = Database.executeQuery(SQL);
            
            while (rs.next()) {
                Object[] ob = new Object[7];
                ob[0] = rs.getString(1);
                ob[1] = rs.getString(2);
                ob[2] = rs.getString(3);
                ob[3] = rs.getString(4);
                ob[4] = rs.getString(5);
                ob[5] = rs.getString(6);
                ob[6] = rs.getString(7);
                
                NoKTP.setText((String) ob[0]);
                Nama.setText((String) ob[1]);
                Tanah.setText((String) ob[2]);
                Lantai.setSelectedItem((String) ob[3]);
                Dinding.setSelectedItem((String) ob[4]);
                Pekerjaan.setSelectedItem((String) ob[5]);
                Penghasilan.setText((String) ob[6]);
            }
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_tabelDataMouseClicked

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        int baris = tabelData.getSelectedRow();
        if (baris != -1) {
            String ID = tabelData.getValueAt(baris, 0).toString();
            String Nama = tabelData.getValueAt(baris, 1).toString();
            String SQL = "DELETE FROM calon where NoKTP = '"+ID+"' AND NAMA = '"+Nama+"'";
            int status = Database.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        selectData();
    }//GEN-LAST:event_HapusActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        //if ("".equals(txtID_NOTA.getText()) || "".equals(txtID_MENU.getText()) || "".equals(txtJumlah.getText()) || "".equals(txtTotal.getText())) {
            //JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        //}else{
            
        //get_id
        int baris = tabelData.getSelectedRow();
        String id = null;
        
        try {
            String sql = "SELECT id_calon FROM calon WHERE "
                    + "noktp = '" + tabelData.getValueAt(baris, 0).toString()+"' AND "
                    + "nama = '" + tabelData.getValueAt(baris, 1).toString()+"'";
            ResultSet rs = Database.executeQuery(sql);
            
            while (rs.next()) {
                Object[] ob = new Object[1];
                ob[0] = rs.getString(1);
                
                id = (String) ob[0];
            }
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, e);
        }

        //normalisasi_tanah
        String tanah = Tanah.getText();
        int ktanah = Integer.parseInt(tanah);
        int ntanah = 0;
        
        if (ktanah < 20 ){
            ntanah = 4;
        }
        if (ktanah > 19 && ktanah <31 ){
            ntanah = 3;
        }
        if (ktanah > 30 && ktanah <41 ){
            ntanah = 2;
        }
        if (ktanah > 40 ){
            ntanah = 1;
        }
        
        //normalisasi_lantai
        String lantai = Lantai.getSelectedItem().toString();
        int nlantai = 0;
        
        if (lantai.equals("Tanah")){
            nlantai = 4;
        }
        if (lantai.equals("Bambu")){
            nlantai = 3;
        }
        if (lantai.equals("Plester")){
            nlantai = 2;
        }
        if (lantai.equals("Keramik")){
            nlantai = 1;
        }
        
        //normalisasi_dinding
        String dinding = Dinding.getSelectedItem().toString();
        int ndinding = 0;
        
        if (dinding.equals("Bambu")){
            ndinding = 4;
        }
        if (dinding.equals("Rumbia")){
            ndinding = 3;
        }
        if (dinding.equals("Kayu Sengon")){
            ndinding = 2;
        }
        if (dinding.equals("Tembok tanpa diplester")){
            ndinding = 1;
        }
        
        //normalisasi_pekerjaan
        String pekerjaan = Pekerjaan.getSelectedItem().toString();
        int npekerjaan = 0;
        
        if (pekerjaan.equals("Buruh")){
            npekerjaan = 4;
        }
        if (pekerjaan.equals("Petani")){
            npekerjaan = 3;
        }
        if (pekerjaan.equals("PNS")){
            npekerjaan = 2;
        }
        if (pekerjaan.equals("Wirausaha")){
            npekerjaan = 1;
        }
        
        //normalisasi_penghasilan
        String penghasilan = Penghasilan.getText();
        int kpenghasilan = Integer.parseInt(penghasilan);
        int npenghasilan = 0;
        
        if (kpenghasilan < 500000 ){
            npenghasilan = 4;
        }
        if (kpenghasilan > 499999 && kpenghasilan <1000001 ){
            npenghasilan = 3;
        }
        if (kpenghasilan > 1000000 && kpenghasilan <3000001 ){
            npenghasilan = 2;
        }
        if (kpenghasilan > 3000000 ){
            npenghasilan = 1;
        }
        
        String SQL = "UPDATE calon SET "
                    + "NoKTP = '"+NoKTP.getText()+"', "
                    + "Nama = '"+Nama.getText()+"',"
                    + "Tanah = '"+Tanah.getText()+"',"
                    + "Lantai = '"+Lantai.getSelectedItem().toString()+"',"
                    + "Dinding = '"+Dinding.getSelectedItem().toString()+"',"
                    + "Pekerjaan = '"+Pekerjaan.getSelectedItem().toString()+"',"
                    + "Penghasilan = '"+Penghasilan.getText()+"',"
                    + "NTanah = '"+ntanah+"',"
                    + "NLantai = '"+nlantai+"',"
                    + "NDinding = '"+ndinding+"',"
                    + "NPekerjaan = '"+npekerjaan+"',"
                    + "NPenghasilan = '"+npenghasilan+"'"
                    + "WHERE ID_CALON = '"+ id +"'";
            int status = Database.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diubah", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diubah", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        //}
    }//GEN-LAST:event_UpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JComboBox<String> Dinding;
    private javax.swing.JButton Hapus;
    private javax.swing.JComboBox<String> Lantai;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField NoKTP;
    private javax.swing.JComboBox<String> Pekerjaan;
    private javax.swing.JTextField Penghasilan;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField Tanah;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelData;
    // End of variables declaration//GEN-END:variables
}
